import { SlideAddons } from '../slides-addons.js?v=4';
import { MoleculeViewerCore } from './molecule-viewer.js';

// Expose to window so inline scripts generated by the parser can access it
window.MoleculeViewerCore = MoleculeViewerCore;

SlideAddons.registerBlockPlugin('molecule', (config, body) => {
    
    // Parse dimensions from config.kv
    const parseDim = (val) => {
        if (!val) return '';
        if (!isNaN(val)) return val + '%';
        return val;
    };

    let style = '';
    if (config.kv.width) style += `width: ${parseDim(config.kv.width)}; `;
    else style += `width: 100%; `;
    
    if (config.kv.height) style += `height: ${parseDim(config.kv.height)}; `;
    else style += `height: 400px; `;
    
    // Parse the body into a bundles dictionary
    // Format: "Name: url"
    const bundles = {};
    const lines = body.split('\n');
    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const colonIdx = trimmed.indexOf(':');
        if (colonIdx > 0) {
            const name = trimmed.substring(0, colonIdx).trim();
            const url = trimmed.substring(colonIdx + 1).trim();
            bundles[name] = url;
        }
    }

    if (Object.keys(bundles).length === 0) {
        return `<div style="color:red; border:1px solid red; padding:10px;">Error: :::molecule block requires at least one 'Name: url' pair in its body.</div>`;
    }

    const containerId = 'molviewer_' + Math.random().toString(36).substring(2, 9);
    const classAttr = config.classes.length > 0 ? ` class="${config.classes.join(' ')}"` : '';

    const viewerConfig = {
        theme: config.kv.theme || 'auto',
        sidebar: config.kv.sidebar || 'visible', // 'visible', 'collapsed', 'hidden'
        initialMolecule: config.kv.initialMolecule || null,
        espScale: config.kv.espScale || null
    };

    return `<div id="${containerId}"${classAttr} style="${style.trim()}"></div>
<script>
// Defer execution slightly to ensure DOM is ready and window.MoleculeViewerCore is bound
setTimeout(() => {
    if (document.getElementById('${containerId}')) {
        new window.MoleculeViewerCore(
            '${containerId}', 
            ${JSON.stringify(bundles)}, 
            ${JSON.stringify(viewerConfig)}
        );
    }
}, 50);
</script>`;
});

window.openMoleculePopup = function(bundles, config = {}) {
    const winId = 'molwin_' + Math.random().toString(36).substring(2, 9);
    
    const win = document.createElement('div');
    win.id = winId;
    win.className = 'mol-window';
    win.style.cssText = `
        position: fixed; 
        top: 10vh; 
        left: 10vw;
        width: 80vw; 
        height: 70vh; 
        background: #fff;
        border-radius: 8px; 
        box-shadow: 0 10px 30px rgba(0,0,0,0.3);
        z-index: ${10000 + document.querySelectorAll('.mol-window').length};
        display: flex; 
        flex-direction: column;
        resize: both; 
        overflow: hidden;
    `;
    
    const titleBar = document.createElement('div');
    titleBar.style.cssText = `
        height: 30px; 
        background: #f0f0f0; 
        border-bottom: 1px solid #ccc;
        cursor: grab; 
        display: flex; 
        justify-content: flex-end; 
        align-items: center;
        padding: 0 10px;
        user-select: none;
    `;
    
    const closeBtn = document.createElement('button');
    closeBtn.innerHTML = '×';
    closeBtn.style.cssText = `
        background: none; border: none; font-size: 24px; cursor: pointer; color: #555;
        line-height: 1; padding: 0; margin: 0;
    `;
    closeBtn.onclick = () => {
        win.remove();
    };
    
    titleBar.appendChild(closeBtn);
    
    const contentDiv = document.createElement('div');
    contentDiv.id = winId + '_content';
    contentDiv.style.cssText = 'flex: 1; width: 100%; height: 100%; position: relative;';
    
    win.appendChild(titleBar);
    win.appendChild(contentDiv);
    document.body.appendChild(win);
    
    // Dragging logic
    titleBar.addEventListener('mousedown', (e) => {
        if (e.target === closeBtn) return;
        titleBar.style.cursor = 'grabbing';
        const rect = win.getBoundingClientRect();
        const offsetX = e.clientX - rect.left;
        const offsetY = e.clientY - rect.top;
        
        // Bring to front
        let maxZ = 10000;
        document.querySelectorAll('.mol-window').forEach(w => {
            const z = parseInt(w.style.zIndex || 10000);
            if (z > maxZ) maxZ = z;
        });
        win.style.zIndex = maxZ + 1;
        
        const onMouseMove = (moveEvent) => {
            win.style.left = (moveEvent.clientX - offsetX) + 'px';
            win.style.top = (moveEvent.clientY - offsetY) + 'px';
        };
        
        const onMouseUp = () => {
            titleBar.style.cursor = 'grab';
            document.removeEventListener('mousemove', onMouseMove);
            document.removeEventListener('mouseup', onMouseUp);
        };
        
        document.addEventListener('mousemove', onMouseMove);
        document.addEventListener('mouseup', onMouseUp);
    });
    
    new window.MoleculeViewerCore(contentDiv.id, bundles, config);
    
    // Render MathJax (e.g. for bundle names in the sidebar)
    setTimeout(() => {
        if (window.MathJax && typeof window.MathJax.typesetPromise === 'function') {
            window.MathJax.typesetPromise([win]).catch(() => {});
        }
    }, 100);
};
