import { SlideAddons } from '../slides-addons.js?v=3';
import { MoleculeViewerCore } from './molecule-viewer.js';

// Expose to window so inline scripts generated by the parser can access it
window.MoleculeViewerCore = MoleculeViewerCore;

SlideAddons.registerBlockPlugin('molecule', (config, body) => {
    
    // Parse dimensions from config.kv
    const parseDim = (val) => {
        if (!val) return '';
        if (!isNaN(val)) return val + '%';
        return val;
    };

    let style = '';
    if (config.kv.width) style += `width: ${parseDim(config.kv.width)}; `;
    else style += `width: 100%; `;
    
    if (config.kv.height) style += `height: ${parseDim(config.kv.height)}; `;
    else style += `height: 400px; `;
    
    // Parse the body into a bundles dictionary
    // Format: "Name: url"
    const bundles = {};
    const lines = body.split('\n');
    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const colonIdx = trimmed.indexOf(':');
        if (colonIdx > 0) {
            const name = trimmed.substring(0, colonIdx).trim();
            const url = trimmed.substring(colonIdx + 1).trim();
            bundles[name] = url;
        }
    }

    if (Object.keys(bundles).length === 0) {
        return `<div style="color:red; border:1px solid red; padding:10px;">Error: :::molecule block requires at least one 'Name: url' pair in its body.</div>`;
    }

    const containerId = 'molviewer_' + Math.random().toString(36).substring(2, 9);
    const classAttr = config.classes.length > 0 ? ` class="${config.classes.join(' ')}"` : '';

    const viewerConfig = {
        theme: config.kv.theme || 'auto',
        sidebar: config.kv.sidebar || 'visible', // 'visible', 'collapsed', 'hidden'
        initialMolecule: config.kv.initialMolecule || null
    };

    return `<div id="${containerId}"${classAttr} style="${style.trim()}"></div>
<script>
// Defer execution slightly to ensure DOM is ready and window.MoleculeViewerCore is bound
setTimeout(() => {
    if (document.getElementById('${containerId}')) {
        new window.MoleculeViewerCore(
            '${containerId}', 
            ${JSON.stringify(bundles)}, 
            ${JSON.stringify(viewerConfig)}
        );
    }
}, 50);
</script>`;
});

// Also expose the Pop-up API for programmatic access
window.openMoleculePopup = function(bundles, config = {}) {
    let modal = document.getElementById('molecule-modal-overlay');
    if (!modal) {
        modal = document.createElement('div');
        modal.id = 'molecule-modal-overlay';
        modal.style.cssText = `
            position: fixed; top:0; left:0; right:0; bottom:0;
            background: rgba(0,0,0,0.8); z-index: 10000;
            display: none; align-items: center; justify-content: center;
        `;
        
        const modalBody = document.createElement('div');
        modalBody.style.cssText = `
            width: 80vw; height: 80vh; background: #fff;
            border-radius: 8px; position: relative; display: flex; flex-direction: column;
        `;
        
        const closeBtn = document.createElement('button');
        closeBtn.innerHTML = '×';
        closeBtn.style.cssText = `
            position: absolute; top: -15px; right: -15px;
            width: 30px; height: 30px; border-radius: 50%;
            background: #e74c3c; color: white; border: 2px solid #fff;
            font-size: 20px; cursor: pointer; z-index: 10001;
        `;
        closeBtn.onclick = () => {
            modal.style.display = 'none';
            // Clear content to free WebGL context
            document.getElementById('molecule-modal-content').innerHTML = '';
        };
        
        const contentDiv = document.createElement('div');
        contentDiv.id = 'molecule-modal-content';
        contentDiv.style.cssText = 'flex: 1; width: 100%; height: 100%;';
        
        modalBody.appendChild(closeBtn);
        modalBody.appendChild(contentDiv);
        modal.appendChild(modalBody);
        document.body.appendChild(modal);
    }
    
    modal.style.display = 'flex';
    new window.MoleculeViewerCore('molecule-modal-content', bundles, config);
};
